### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by askeblad**
src/Test/HUnit/Text.hs

### CODE REVIEW

**Review by bergmark — APPROVED** [review]
Thanks a bunch!

**Comment by askeblad** [comment]
@sol the commit displays a "Verified"  button which GitHub added

here's the fix if a Member would implement the change themself (then I would delete my fork)

src/Test/HUnit/Text.hs

```diff
- -- | Accumulates persistent lines (dropping progess lines) for return by
+ -- | Accumulates persistent lines (dropping progress lines) for return by

**Comment by bergmark** [comment]
> the commit displays a "Verified" button which GitHub added

Not sure i follow, is that an issue?


Also not sure what's going on with CI, I'll just merge this. @sol has the hspec org run run out of GHA credits, perhaps?

**Comment by askeblad** [comment]
@bergmark 

@sol closed yesterday an hspec/hspec PR and thereafter made the comment

@askeblad bot commits should be marked as such.

**Comment by sol** [comment]
@askeblad to clarify, my issue with that `hspec` PR is that it did not contribute anything (it's a vendored dependency, we don't want to modify it, not even fix typos).  Whether it's actually a bot commit, or if a human did it semi-automated is not my main concern here.

That said, this PR is an improvement and of course I'm fine with it.

**Comment by sol** [comment]
@bergmark the issue with CI is that GitHub dropped support for `ubuntu-16.04`.  I'll look into it some time soon.

**Pull request merged**
