### PR TITLE
Added the function 'runTestTTAndExit' to 'Test.HUnit.Text'.

### PR DESCRIPTION
**Pull request by clintonmead**
This is my first pull request on Github, my apologies if I've got something wrong.

This simply adds a function 'runTestTTAndExit' to the module 'Test.HUnit.Text', which just calls 'runTestTT', checks the counts, and if the failure and error count is zero, exits to the OS with success, otherwise exits with failure. I found myself rewriting this myself often for my tests, so I thought it might as well be added to the module proper.

### CODE REVIEW

**Comment by sol** [comment]
That `HUnit` does not use `exitFailure` on failing tests is not the most fortunate design decision.  The same is true for `QuickCheck`.

The established solution for this is to use a testing framework.  There are a couple of options to choose from:

 - `test-framework`
 - `tasty`
 - `HTF`
 - `hspec`

Maybe not surprisingly, [`hspec`](https://hspec.github.io/) is my preferred option.  But all of them, except for `tasty`, allow you to use `HUnit` (`tasty` ships with a modified copy of an outdated version of `HUnit`). All of them will exit with `exitFailure` on failing test cases, and all of them support `QuickCheck`.

(full disclosure, I'm the maintainer and main author of `hspec`)

**Comment by sol** [comment]
That said, I guess I can be convinced to merge this if you insist to use plain `HUnit`.

**Comment by clintonmead** [comment]
`hspec` should do the job fine, thanks!

It might be worth putting a link to `hspec` somewhere in the `HUnit` docs, as both `HUnit` and `hspec` say they're "testing frameworks" in their descriptions, and there's nothing there that suggests that it's a potentially good idea to use the "unit testing framework `HUnit`" as a subcomponent of another "testing framework: `hspec`"

**Comment by fumieval** [comment]
@sol I'd like this to be merged. Going through all those test frameworks can be a difficulty for beginners and even I wish HUnit could exit by itself.

**Comment by sol** [comment]
I can't reopen this issue as @clintonmead delete his copy of the repo.  We have https://github.com/hspec/HUnit/pull/28 instead.

@fumieval btw, if you think there is anything we can do to make http://hspec.github.io/ more accessible, please let me know.

**Pull request closed without merging**
